const { Client } = require('discord.js-selfbot-v13');
const client = new Client({ checkUpdate: false });

// ================= CONFIGURACIÓN =================
const TOKEN = 'MTQ3OTc1NTkzMDQ4MzY5MTYxMA.G7zzXC.CBeZb8MojNHXKqFdVwfi4u0h7DbEg-J3jRk41Y'; // Recuerda que el token cambia si cambiaste clave
const ID_CANAL = '1484027185961369770'; 

const MENSAJES = [
    ".SUS CULITOS SE ENTREGAN WEY, PERRAS, LOS BOTS NO TIENEN NADA Q VER CON QUE SE SALGA PORQUE SUS ANOS CON UN TIPO DE BRUJERIA HICIERON Q CADA VEZ Q SACASEN A UNA SACASEN MI CHOTA DE SUS BOCAS JSJJSJ ES MAS NI BOT USO PORQUE MI VERGA ES INMORTAL CHE MI VERGA ES COLOSALMENTE DOMADORA XDDDDDDDDDDDDDJDKDJKDJDKDDKDJKDJDKDJDKDJ @SOBOSLAI1 @ELNOMBREDESERGIOCANALES @M4NHUNT3RR @TIBURONJRPRIME @REYNEPTUNOTESACALOSPEDOS @EVERYONE TODAS VAYAN A POR MI VERGA PUTITAS DESNALGADAS JKSJDKSJKDJSKDJSKDJSKDJKSDJSJDKJSKDJSHDJAKDJKAJKAJWJSJAKJSKAJSKAJSKAJSKJAKDJAKDJAKDJAKJS",
    "COMO SE EMOCIONA LA MAMI EDUARDA APENAS VE QUE MI PITO NO MANDA ALGO XDDDDDDDDD, PIENSA QUE SON COSAS DE BANEO PERO A EL FINAL VE QUE MI PITO VUELVE SE ENOJA LA MAMI XDDDDDDDDDDD , MAMI EDUARDA NO TIENE NADA QUE VER LO QUE TU CULITO PIENSA YA QUE DENUNCIAN POR COSAS EXTERNAS Y DISCORD SE PONE DE PUTITA XDDDDDDDDDDDDDDDDD, TE EMOCIONAS PERRA PERO SIEMPRE REGRESO A COMERTE EL CULITO DE PUTITA MILF WEY JSJSJSJSJSJ https://youtu.be/qBCwnC_yqos?si=2s_0MbgGtiybFsdR @everyone",
    "COMO SE EMOCIONA LA MAMI EDUARDA APENAS VE QUEMIPITO NO MANDA ALGO XDDDDDDDDD, PIENSA QUE SON COSAS DE BANEO PERO A EL FINAL VE QUE MI PITO VUELVE SE ENOJA LA MAMI XDDDDDDDDDDD , MAMI EDUARDA NO TIENE NADA QUE VER LO QUE TU CULITO PIENSA YA QUE DENUNCIAN POR COSAS EXTERNAS Y DISCORD SE PONE DE PUTITA XDDDDDDDDDDDDDDDDD, TE EMOCIONAS PERRA PERO SIEMPRE REGRESO A COMERTE EL CULITO DE PUTITA MILF WEY JSJSJSJSJSJ https://youtu.be/qBCwnC_yqos?si=2s_0MbgGtiybFsdR @everyone",
    ".SUS CULITOS SE ENTREGAN WEY, PERRAS, LOS BOTS NO TIENEN NADA Q VER CON QUE SE SALGA PORQUE SUS ANOS CON UN TIPO DE BRUJERIA HICIERON Q CADA VEZ Q SACASEN A UNA SACASEN MI CHOTA DE SUS BOCAS JSJJSJ ES MAS NI BOT USO PORQUE MI VERGA ES INMORTAL CHE MI VERGA ES COLOSALMENTE DOMADORA XDDDDDDDDDDDDDJDKDJKDJDKDDKDJKDJDKDJDKDJ @SOBOSLAI1 @ELNOMBREDESERGIOCANALES @M4NHUNT3RR @TIBURONJRPRIME @REYNEPTUNOTESACALOSPEDOS @EVERYONE TODAS VAYAN A POR MI VERGA PUTITAS DESNALGADAS JKSJDKSJKDJSKDJSKDJSKDJKSDJSJDKJSKDJSHDJAKDJKAJKAJWJSJAKJSKAJSKAJSKAJSKJAKDJAKDJAKDJAKJS",
    "CULITO DE MAMI EDUARDA PUTITA QUE DIFAMA WEY JSJSJSJSJS @everyone",
    ".SUS CULITOS SE ENTREGAN WEY, PERRAS, LOS BOTS NO TIENEN NADA Q VER CON QUE SE SALGA PORQUE SUS ANOS CON UN TIPO DE BRUJERIA HICIERON Q CADA VEZ Q SACASEN A UNA SACASEN MI CHOTA DE SUS BOCAS JSJJSJ ES MAS NI BOT USO PORQUE MI VERGA ES INMORTAL CHE MI VERGA ES COLOSALMENTE DOMADORA XDDDDDDDDDDDDDJDKDJKDJDKDDKDJKDJDKDJDKDJ @SOBOSLAI1 @ELNOMBREDESERGIOCANALES @M4NHUNT3RR @TIBURONJRPRIME @REYNEPTUNOTESACALOSPEDOS @EVERYONE TODAS VAYAN A POR MI VERGA PUTITAS DESNALGADAS JKSJDKSJKDJSKDJSKDJSKDJKSDJSJDKJSKDJSHDJAKDJKAJKAJWJSJAKJSKAJSKAJSKAJSKJAKDJAKDJAKDJAKJS @everyone",
    "COMO SE EMOCIONA LA MAMI EDUARDA APENAS VE QUE MI PITO NO MANDA ALGO XDDDDDDDDD, PIENSA QUE SON COSAS DE BANEO PERO A EL FINAL VE QUE MI PITO VUELVE SE ENOJA LA MAMI XDDDDDDDDDDD , MAMI EDUARDA NO TIENE NADA QUE VER LO QUE TU CULITO PIENSA YA QUE DENUNCIAN POR COSAS EXTERNAS Y DISCORD SE PONE DE PUTITA XDDDDDDDDDDDDDDDDD, TE EMOCIONAS PERRA PERO SIEMPRE REGRESO A COMERTE EL CULITO DE PUTITA MILF WEY JSJSJSJSJSJ https://youtu.be/qBCwnC_yqos?si=2s_0MbgGtiybFsdR @everyone",
    "COMO SE EMOCIONA LA MAMI EDUARDA APENAS VE QUE MI PITO NO MANDA ALGO XDDDDDDDDD, PIENSA QUE SON COSAS DE BANEO PERO A EL FINAL VE QUE MI PITO VUELVE SE ENOJA LA MAMI XDDDDDDDDDDD , MAMI EDUARDA NO TIENE NADA QUE VER LO QUE TU CULITO PIENSA YA QUE DENUNCIAN POR COSAS EXTERNAS Y DISCORD SE PONE DE PUTITA XDDDDDDDDDDDDDDDDD, TE EMOCIONAS PERRA PERO SIEMPRE REGRESO A COMERTE EL CULITO DE PUTITA MILF WEY JSJSJSJSJSJ https://youtu.be/qBCwnC_yqos?si=2s_0MbgGtiybFsdR @everyone"
];

const INTERVALO = 5000; // 5 segundos exactos
// =================================================

client.on('ready', async () => {
    console.log(`✅ BOT DE SPAM CONECTADO COMO: ${client.user.tag}`);
    
    const channel = await client.channels.fetch(ID_CANAL);
    
    let contador = 0;
    setInterval(async () => {
        try {
            const frase = MENSAJES[Math.floor(Math.random() * MENSAJES.length)];
            await channel.send(frase);
            contador++;
            console.log(`🚀 Mensaje #${contador} enviado: ${frase}`);
        } catch (err) {
            console.log("⚠️ Error de envío (posible Rate Limit).");
        }
    }, INTERVALO);
});

client.login(TOKEN);
